/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "amalfi": {
    "base": "amalfi",
    "width": 3840,
    "height": 2430,
    "fallbackWidth": 1920,
    "fallbackHeight": 1215,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "boat": {
    "base": "boat",
    "width": 1998,
    "height": 1108,
    "fallbackWidth": 800,
    "fallbackHeight": 444,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cathedral": {
    "base": "cathedral",
    "width": 2048,
    "height": 1536,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1152,
    "height": 864,
    "fallbackWidth": 1152,
    "fallbackHeight": 864,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 3840,
    "height": 2536,
    "fallbackWidth": 1920,
    "fallbackHeight": 1268,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 3840,
    "height": 2267,
    "fallbackWidth": 1920,
    "fallbackHeight": 1134,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 511,
    "height": 768,
    "fallbackWidth": 511,
    "fallbackHeight": 768,
    "widths": [
      320,
      480
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "harbour": {
    "base": "harbour",
    "width": 3840,
    "height": 2267,
    "fallbackWidth": 1920,
    "fallbackHeight": 1134,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3840,
    "height": 1206,
    "fallbackWidth": 1920,
    "fallbackHeight": 603,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3840,
    "height": 2536,
    "fallbackWidth": 1920,
    "fallbackHeight": 1268,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "paestum": {
    "base": "paestum",
    "width": 3840,
    "height": 2269,
    "fallbackWidth": 1920,
    "fallbackHeight": 1135,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "pompeii": {
    "base": "pompeii",
    "width": 511,
    "height": 768,
    "fallbackWidth": 511,
    "fallbackHeight": 768,
    "widths": [
      320,
      480
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "positano": {
    "base": "positano",
    "width": 359,
    "height": 300,
    "fallbackWidth": 359,
    "fallbackHeight": 300,
    "widths": [
      320
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 1152,
    "height": 864,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "ravello": {
    "base": "ravello",
    "width": 1100,
    "height": 1650,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "salerno-centro": {
    "base": "salerno-centro",
    "width": 2816,
    "height": 2112,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "salerno-waterfront": {
    "base": "salerno-waterfront",
    "width": 3840,
    "height": 1042,
    "fallbackWidth": 1920,
    "fallbackHeight": 521,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "vesuvius": {
    "base": "vesuvius",
    "width": 3072,
    "height": 2304,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "vineyard": {
    "base": "vineyard",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 2848,
    "height": 4272,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
